### PR TITLE
Feature/14 integrate corp branding

### PR DESCRIPTION
**Pull request by eurolife**
CPR corporate branding has been incorporated into the UI.

### CODE REVIEW

**Comment by kdutia** [comment]
@eurolife it all functions well, but the fonts look a bit heavy to me. I notice you've given them a weight of 700 for all headers and different sizes in the CSS. Would it be possible to amend the CSS to coincide with the typography section of the [brand guidelines](https://drive.google.com/drive/u/1/folders/1vhbgmR6x5b6E2Y_Z8Tp3ygtyJAd03ybY)?

**Comment by eurolife** [comment]
> @eurolife it all functions well, but the fonts look a bit heavy to me. I notice you've given them a weight of 700 for all headers and different sizes in the CSS. Would it be possible to amend the CSS to coincide with the typography section of the [brand guidelines](https://drive.google.com/drive/u/1/folders/1vhbgmR6x5b6E2Y_Z8Tp3ygtyJAd03ybY)?

I'm just excited the tests finally passed! I think slow network connection was the issue so I added a wait command before it scrolled. I will look at the heading sizes.

**Comment by eurolife** [comment]
@kdutia just pushed up the font styling changes.

**Review by kdutia — APPROVED** [review]
Looks great 🌟

**Pull request merged**
