### PR TITLE
Feature: Add improved document upload url

### PR DESCRIPTION
**Pull request by joel-wright**

### CODE REVIEW

**Review by diversemix — APPROVED** [review]
looking good

**Comment by joel-wright** [comment]
If you're happy with this as a concept I'll work on adding a few tests for the functionality

**Comment by joel-wright** [comment]
There's not much I can really do to test this because it's such a thin wrapper around s3 client calls... I'm suggesting it's ready, but open to testing suggestions...

**Comment by diversemix** [comment]
I agree its part of a bigger whole - lets consider testing later and get this in :+1:

**Pull request merged**
