### PR TITLE
Feat 351 get action

### PR DESCRIPTION
**Pull request by opyate**
Get action by ID.

### CODE REVIEW

**Review by joel-wright — COMMENTED** [review]
It would be nice if we also had tests validating the behaviour when the action does not exist, when the request is supplied with invalid auth headers & no auth headers.

**Comment by opyate** [comment]
> It would be nice if we also had tests validating the behaviour when the action does not exist, when the request is supplied with invalid auth headers & no auth headers.

Indeed, but I think auth is tested once somewhere, and 404 is just a thing you perhaps have to trust that starlette/fastapi codebases have already tested?

**Comment by joel-wright** [comment]
> > It would be nice if we also had tests validating the behaviour when the action does not exist, when the request is supplied with invalid auth headers & no auth headers.
> 
> Indeed, but I think auth is tested once somewhere, and 404 is just a thing you perhaps have to trust that starlette/fastapi codebases have already tested?

I'm not sure I follow your reasoning here - all the API calls must be authenticated and it looks like we're enforcing that with an endpoint specific `Depends()`, so we need to verify that all the API endpoints require auth. It's not a case of testing whether the auth API works, but that these specific API calls have the appropriate authentication requirements enabled. Have I missed a test elsewhere that validates that all our endpoints require appropriate auth?

Also, it doesn't look to me like starlette/fastapi are handing the 404 - we are explicitly implementing the 404 response in our own `get_action()` function and there's no test for that code path, so how do I know the code is working as expected?

**Comment by opyate** [comment]
> we are explicitly implementing the 404 response in our own `get_action()` function

Ah, sorry - I read that as testing missing endpoints, or verifying that endpoints exist.

> all the API calls must be authenticated and it looks like we're enforcing that with an endpoint specific Depends()

Noted. Test coming up!

**Review by joel-wright — APPROVED** [review]
LGTM

**Pull request merged**
