### PR TITLE
Fix 607 indexer extra docs

### PR DESCRIPTION
**Pull request by kdutia**
Add non english pdfs and htmls to Opensearch index. Shouldn't be merged until #610 is, as I branched from that branch. The PR is currently pointing at the branch for #610 so changes are easily viewable.

All documents without text outputs from the pdf2text pipeline are now just loaded in with their descriptions and titles searchable. The effect of some documents only having descriptions and titles on search ranking should be investigated.

### CODE REVIEW

**Comment by kdutia** [comment]
`document_source_url` now added to all docs in this PR

**Review by stefl14 — APPROVED** [review]
Clear to me. Looks fine when other merges complete.

**Review by joel-wright — APPROVED** [review]
LGTM

**Comment by joel-wright** [comment]
tests fixed in another branch

**Pull request merged**
